services:
  - type: web
    name: hot-records-shop
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production

databases:
  - name: hot-records-shop-db
    plan: free
