services:
  - type: web
    name: hot-records-shop
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
    preDeployCommand: "bundle exec rails db:migrate && bundle exec rails db:seed"

databases:
  - name: hot-records-shop-db
    plan: free
