services:
  - type: web
    name: hot-records-shop
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
    startCommand: "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"

databases:
  - name: hot-records-shop-db
    plan: free
