# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65591d554a2735d662c4d7f932d0cc580bdba8ba86e1d4f517c771f66251ba8f3a8589714ea688e80ad15988874c3c8df996c16dc84dc528170d438dce7ec7f6

test:
  secret_key_base: 0700507f6a80a0b008f526d7ff82f4c11d8d4f36da72a4e45dd276c642042815a7e93fd1529a3f587c97cd522fdc69bb41704f86b9402170f171422827c0097d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
